### ISSUE TITLE
Ilk eksik integer degeri bulma problemi

### ISSUE THREAD

**Issue by msusur** [msusur/kodlama-pratikleri#15]
@eypaksu'nun #11 'deki cozumunde `TreeSet` kullanmasi problemin cozumune aykiri mi? 

@cevherkarakoc

**Comment by BTaskaya** [comment]
@ayyucedemirbas

**Comment by cevherkarakoc** [comment]
Burada tekrar belirteyim`TreeSet` kullanımındaki problem, sınıfının zaten kendi içinde otomatik sıralama yapıyor olması.

**Comment by eypaksu** [comment]
array i direk siralama konusunda bir sinirlama var yani direk siralarsan muhtemelen O(n Log n ) gibi bir compexity e ulasacaksin fakat treeSet add complexity log (n) yani O(n) den kucuk dolayisiyla sorun yok.

**Comment by cevherkarakoc** [comment]
@eypaksu Tek bir elemanın eklenmesi O(log(n)). N tane eleman ekleyince O( n * log(n)) olacaktır.

**Comment by eypaksu** [comment]
@cevherkarakoc haklisin galiba N,.., 2N,.., 3N... dogru cikiyor,  sanirim burada inverviewer katsayiya dikkat etmedi. Bu arada yaklasik 1 sene evvel girdigim bir interview di yani O(XN) de olabilir kisitlama, soruyu bu sekilde guncelleyebiliriz yada baska bir cozum vardir illaki.

**Comment by cevherkarakoc** [comment]
@eypaksu Soruda kısıtları kaldırıp, hedefi en düşük karmaşıklığı bulmak yapabiliriz.

**Comment by msusur** [comment]
Bununla ilgili bir sey yapacak miyiz? Kisitlarin hangilerini kaldirmayi dusunuyoruz?

**Comment by eypaksu** [comment]
bir pull request daha yolladim bu issue ile ilgili. #23

**Comment by msusur** [comment]
merge ettim, simdilik kapatiyorum bunu. gerekirse tekrar acariz.
