### ISSUE TITLE
Python Sürümü Olarak Sadece Py3 Desteklenmeli

### ISSUE THREAD

**Issue by BTaskaya** [msusur/kodlama-pratikleri#38]
Python2 şuandan itibaren sadece security güncellemeleri ve bug fix alacak. Ve 2018 yılında çok spesifik bir sebep yoksa yazilmamali (2020'de tamamen biticek) 

Default olarak Python sürümünü 3 kabul etmeliyiz ve 2 ile yazılmış çözümleri kaldirmaliyiz.

**Comment by msusur** [comment]
hangi cozumler bu kapsama giriyor?

**Comment by cevherkarakoc** [comment]
Şu an Python 2 ile yazılmış çözüm yok. Daha önce bir PR da olmuştu o da değiştirildi.

**Comment by msusur** [comment]
O zaman simdilik kapatiyorum bunu.

**Comment by BTaskaya** [comment]
@msusur Gelecek PR'lara referans niteliğinde yazdım.
