### ISSUE TITLE
c# cozumlerinde Console.WriteLine yerine Debug.Assert kullanilmasi

### ISSUE THREAD

**Issue by msusur** [msusur/kodlama-pratikleri#44]
Cozumlerde `Console.WriteLine` cok fazla goruyorum, farkli test case'leri karsilamasi icin `Debug.Assert` kullanilmasini oneriyorum.

Detaylar icin: [Debug.Assert Method (System.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.assert?view=netframework-4.7.2)

**Comment by enderahmetyurt** [comment]
bu konuyu programalama dili seviyesinde değil de genel olarak ele alsak daha iyi. Test yazımını yaygınlaştırmak adına Readme güncellemesi yapıp, soruları da aynı şekilde güncellemek gerekiyor. sonrasında ise testsiz kodu merge etmemek.
