### ISSUE TITLE
Sorulari Readme'ye eklemece

### ISSUE THREAD

**Issue by msusur** [msusur/kodlama-pratikleri#66]
Duydum ki @enderahmetyurt #61 ve #63 sorularini `Readme.md`ye eklemek icin can atiyormus. Ben de mutlu olsun diye issue actim :)

**Comment by enderahmetyurt** [comment]
ehehe aslında pek öyle değil. Yeni gelenlerin PR bakmak aklına gelmeyebilir README'de durması daha doğru bence. Hacktoberfest için. Zaten eklediğim sorulara gelen PR'lara ben label olarak hacktoberfest ekleyeceğim. ;)

**Comment by enderahmetyurt** [comment]
#67 solved :)

**Comment by msusur** [comment]
Elinize saglik @enderahmetyurt ve @cevherkarakoc :)
